using System.Windows;
using AdbInstallerApp.ViewModels;

namespace AdbInstallerApp.Views
{
    /// <summary>
    /// Interaction logic for DeviceOptionsDialog.xaml
    /// </summary>
    public partial class DeviceOptionsDialog : Window
    {
        public DeviceOptionsDialog()
        {
            // InitializeComponent will be generated by XAML compiler
            InitializeComponent();
        }

        public DeviceOptionsDialog(object dataContext) : this()
        {
            DataContext = dataContext;
        }

        private void OkButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = true;
        }

        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
        }

        private void Window_Unloaded(object sender, RoutedEventArgs e)
        {
            if (DataContext is DeviceOptionsViewModel vm)
            {
                // Cleanup if needed
            }
        }
    }
}
